Character Sheet connected to Character Session, Dice Roller connected…
ngutn24/RollBuddy pull request #34
Opened 2022-05-05 08:35 UTC by Esauidk

… to Character Session

2022-05-05 23:49 UTC, jongwon1-1932256 requested changes
Could you just change the Session Id into a string

2022-05-06 00:34 UTC, leftl commented
have you guys considered using UUIDs?
https://www.geeksforgeeks.org/java-util-uuid-class-java/

2022-05-06 09:05 UTC, Esauidk commented
> Could you just change the Session Id into a string

Addressed and added to this PR

2022-05-07 07:10 UTC, jongwon1-1932256 approved these changes

2022-05-07 07:51 UTC, merged